stages:
  - security

semgrep-sast:
  image: python:3.10
  stage: security
  before_script:
    - pip install semgrep
  script:
#    - semgrep --config=auto --json --output=semgrep-results.json
    - semgrep --config=custom-rules.yaml .
  artifacts:
    paths:
      - semgrep-results.json
